### ISSUE TITLE
学习强国辅助 - 专项答题错误

### ISSUE THREAD

**Issue by liuhxq990619** [jiajia172000/python_project#2]
学习强国自动辅助 V2.30 中，专项答题无法使用，具体表现为进入专项题目列表之后无法自动进入指定题目，手动进入题目后无法实现自动答题。

学习强国版本号：2.15.1

将作者原文件 qiangguo_shuafen.py 第 385 行的 `ti_num = -1` 改为 `ti_num = 0` 后可正常答题。

**Comment by jiajia172000** [comment]
感谢，我已在后续版本中发现问题并修复BUG
