### ISSUE TITLE
学习强国辅助 - 每周答题错误

### ISSUE THREAD

**Issue by liuhxq990619** [jiajia172000/python_project#3]
学习强国自动辅助 V2.30 中，每周答题出现偶发性错误，具体表现为当完成所有每周答题之后，程序不会自动识别列表结尾从而跳出循环，而是一直尝试获取最新题目，直至触发 1 小时限制后结束线程。

学习强国版本号：2.15.1

**Comment by jiajia172000** [comment]
感谢，已修复BUG
