### ISSUE TITLE
填空类型的全错，请问需要选择什么输入法吗?

### ISSUE THREAD

**Issue by solife2020** [jiajia172000/python_project#4]
填空类型的全错，填写都是：重大机制，请问需要选择什么输入法吗?

**Comment by solife2020** [comment]
点击查看答案红字中有内容，但填入的答案都是错误的。

**Comment by jiajia172000** [comment]
程序原理是：每日答题的填空题，截图提示中信息，将除红色部份外其他部分出去，用PYTESSERAT识别汉字，如果得到的内容字数与空格数匹配就填入，如果不匹配就说明识别有问题，就随便填写内容。但这不影响每日答题的得分，逻辑是如果分数不够会再次答每日答题，直到够了为止。
